---
dontChroot: false
timeout: 999
script:
    - "mv /etc/mkinitcpio.conf.ez /etc/mkinitcpio.conf"
    - "mv /etc/mkinitcpio.d/linux.preset.ez /etc/mkinitcpio.d/linux.preset"
    - "rm -rf /etc/mkinitcpio.conf.d/archiso.conf"
