---
dontChroot: false
timeout: 30
script:
    - "rm -rf /etc/arch-release"
    - "echo DISTRIB_ID=\"Femboy\" > /etc/lsb-release"
    - "echo DISTRIB_RELEASE=\"rolling\" >> /etc/lsb-release"
    - "echo DISTRIB_DESCRIPTION=\"Femboy Linux\" >> /etc/lsb-release"
