# Nyarch custom settings
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the mvezmkinit.conf files shell process job.
#
---
dontChroot: false
timeout: 999
script:
    - "mv /etc/mkinitcpio.d/linux.preset.ez /etc/mkinitcpio.d/linux.preset"
    - "mv /etc/mkinitcpio.conf.ez /etc/mkinitcpio.conf"
    - "rm /etc/mkinitcpio.conf.d/archiso.conf"
